defmodule Holidays do

  # All clauses of `on` exept the initial defaults header and final catch-all
  # should be generated by macros.
  # Writing out implementations for now to get the API right.
  def on(date, regions \\ [])
  def on({_, 1, 1}, [:us]), do: [%{name: "New Year's Day"}]
  def on({_year, month, day} = date, regions) do
    wday = :calendar.day_of_the_week(date)
    week = div(day, 7)
    on(month, week, wday, regions)
  end
  def on(_date, _regions), do: []

  def on(month, week, wday, regions \\ [])
  def on(1, 3, 1, [:us]), do: [%{name: "Martin Luther King, Jr. Day"}]
  def on(_month, _week, _wday, _regions), do: []
end
